# Generated by Django 4.0.3 on 2022-04-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='files',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
