# Generated by Django 4.0.3 on 2022-04-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='files',
            new_name='image_upload',
        ),
    ]
